default_config:
logger:
  default: error
  logs:
    custom_components.myfitnesspal: debug

# Remove if debug needed
# debugpy:

# Setup old school or through integrations
# sensor:
#   - platform: my_fitnesspal
#     username: your_user_name
#     password: !secret password # If this is setup in new container, remember to add the file secrets.yaml